### ISSUE TITLE
there is no output from 3dposebaseline

### ISSUE THREAD

**Issue by qweasdzxc110** [errno-mmd/VMD-Lifting#3]
may i ask a question?when i run MotionTraceBulk.bat in win10, openpose & frcn can run successfully but fail with 3dposebaseline . In output folder, i find that there are complete json file of openpose'output and depth png of frcn , but smoothed.txt and pos.txt have nothing (0 Kb).I have tried three times, but there is no difference between results.
--

**Comment by errno-mmd** [comment]
It is not related to VMD-Lifting.
I guess you are asking about https://github.com/miu200521358/motion_trace_bulk
